WIFI_SSID = "bindsoft"
WIFI_PASSWORD = "bindsoft24"

MQTT_HOST = "163.152.213.111"
MQTT_PORT = 1883

DEVICE_ID = "pico-safe-001"
ZONE_ID = "room-1"

PUBLISH_INTERVAL_SECONDS = 5

PIN_DHT = 16
DHT_SENSOR_TYPE = "DHT11"
PIN_MOTION = 17
PIN_GAS_ADC = 26
PIN_LIGHT_ADC = 27

ENABLE_DHT = True
ENABLE_MOTION = True
ENABLE_GAS = False
ENABLE_LIGHT = True


